src/Command/BlacklistCommonCommand.php, tests/Command/BlacklistListCommandTest.php
|Q            |A  |
|---          |---|
|Bug Fix?     |yes|
|New Feature? |no |
|BC Breaks?   |no |
|Deprecations?|no |
|Tests Pass?  |yes|
|Fixed Tickets|   |
|License      |MIT|
=> fix broken tests

src/Command/BlacklistCommonCommand.php, src/DependencyInjection/RollerworksPasswordStrengthExtension.php, tests/Blacklist/SqliteProviderTest.php, tests/Command/BlacklistCommandTestCase.php, tests/Command/BlacklistDeleteCommandTest.php, tests/Command/BlacklistUpdateCommandTest.php, tests/DependencyInjection/ExtensionTest.php, tests/bootstrap.php
@sstok requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/rollerworks/PasswordStrengthBundle/
=> Scrutinizer Auto-Fixes

.travis.yml, composer.json
|Q            |A  |
|---          |---|
|Bug Fix?     |no |
|New Feature? |yes|
|BC Breaks?   |yes|
|Deprecations?|no |
|Fixed Tickets|   |
|License      |MIT|
=> bump minimum Symfony version 2.3 LTS

.travis.yml, composer.json, src/Validator/Constraints/BlacklistValidator.php, src/Validator/Constraints/PasswordRequirementsValidator.php, src/Validator/Constraints/PasswordStrengthValidator.php, tests/Validator/BlacklistValidationTest.php, tests/Validator/LegacyBlacklistValidation2Dot4ApiTest.php, tests/Validator/LegacyBlacklistValidationLegacyApiTest.php, tests/Validator/LegacyPasswordRequirementsValidator2Dot4ApiTest.php, tests/Validator/LegacyPasswordRequirementsValidatorLegacyApiTest.php, tests/Validator/LegacyPasswordStrength2Dot4ApiTest.php, tests/Validator/LegacyPasswordStrengthLegacyApiTest.php, tests/Validator/PasswordRequirementsValidatorTest.php, tests/Validator/PasswordStrengthTest.php
=> Compatibility with 2.5 API #37

src/Command/BlacklistDeleteCommand.php, src/Command/BlacklistUpdateCommand.php
Fix last errors in Sensiolabs Insight (before Platinum medal)
=> Remove unused statements

docs/blacklist.md
=> Fix: Right Constraint name

src/Resources/translations/validators.nl.xlf
|Q            |A  |
|---          |---|
|Bug Fix?     |yes|
|New Feature? |no |
|BC Breaks?   |no |
|Deprecations?|no |
|Fixed Tickets|   |
|License      |MIT|
=> Fix wrong message in nl translation

src/Resources/translations/validators.de.xlf, src/Resources/translations/validators.es.xlf, src/Resources/translations/validators.it.xlf
I included the bundle translations in the file sent to our contractor translating Incenteev into German, Spanish and Italian. So here are these messages.
=> Add more translations

.travis.yml, composer.json, tests/Blacklist/ArrayProviderTest.php, tests/Blacklist/ChainProviderTest.php, tests/Blacklist/NoopProviderTest.php, tests/Blacklist/SqliteProviderTest.php, tests/Command/BlacklistCommandTestCase.php, tests/Command/BlacklistDeleteCommandTest.php, tests/Command/BlacklistListCommandTest.php, tests/Command/BlacklistPurgeCommandTest.php, tests/Command/BlacklistUpdateCommandTest.php, tests/DependencyInjection/ExtensionTest.php
Lets hope this fixes the Travis nightly failure.
=> Fix PHPUnit compatibility

tests/DependencyInjection/ExtensionTest.php
Related to https://github.com/symfony/symfony/pull/22024
Let's hope I don't have to fix this again 😅
=> Fix tests failure for Symfony 3.3-dev

tests/DependencyInjection/ExtensionTest.php
Instead of testing whether they are in fact registered this now check if the Factory is able to load them. This less fragile for internal changes and removes the BC layer.
=> Fix broken tests for Symfony 3.3-dev

src/Resources/translations/validations.cs.xlf
=> Add Czech translation

.travis.yml, composer.json
| BC breaks?    | no (version bump is not a BC break)
=> Remove support for EOL PHP versions and HHVM

.travis.yml, composer.json, src/Resources/config/blacklist.xml
=> Fix service definition of BlacklistValidator

src/DependencyInjection/RollerworksPasswordStrengthExtension.php, tests/DependencyInjection/ExtensionTest.php
=> Don’t register abstract commands

.travis.yml
=> [CI] Fix broken build with deps=low

.travis.yml, composer.json, tests/DependencyInjection/ExtensionTest.php
=> Fix Symfony 4 compatibility

.php_cs, .travis.yml, composer.json, phpstan.neon, tests/DependencyInjection/ConfigurationTest.php
| BC breaks?    | yes
| Fixed tickets |
=> Use modern php versions

src/DependencyInjection/Configuration.php
=> Fix forward compatibility with Symfony 5

.gitignore, .travis.yml, composer.json, phpstan.neon, src/DependencyInjection/RollerworksPasswordStrengthExtension.php, tests/DependencyInjection/ExtensionTest.php
Note: This properly needs a more permanent solution like phpqa
=> Fix broken linting

.travis.yml, composer.json, phpstan.neon, tests/DependencyInjection/ExtensionTest.php
=> Add support for Symfony 5

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yaml, .gitignore, composer.json
| New feature?  | yes
Note: This uses a fork of SymfonyTest, as the upstream is not fully compatible yet
=> Allow Symfony 6

.github/workflows/ci.yaml, composer.json
| BC breaks?    |no
| Fixed tickets |
=> Update OS version for works flows

src/DependencyInjection/RollerworksPasswordStrengthExtension.php, tests/DependencyInjection/MakeAllServicesPublicPass.php
| Deprecations? | fixed
| Fixed tickets | -
Hey,
Fixed deprecation messages! Pull request ready. Check it out!
Thank you :pray:
=> Fix Symfony 6.x deprecations

src/DependencyInjection/RollerworksPasswordStrengthExtension.php
| Deprecations? | yes
| Fixed tickets |  
=> fix deprecation for di Extension
